name: SKOG302
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_1
  - bottleneck=1.3.5=py39h080aedc_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py39h415ef7b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.9.24=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_0
  - cfitsio=3.470=h2bbff1b_7
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=py39haa95532_0
  - colorama=0.4.5=py39haa95532_0
  - curl=7.84.0=h2bbff1b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dash=1.8.0=py_0
  - dash-core-components=1.7.0=py_0
  - dash-html-components=1.0.2=py_0
  - dash-renderer=1.2.3=py_0
  - dash-table=4.6.0=py_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h6c2663c_0
  - fiona=1.8.13.post1=py39h758c064_0
  - flask=1.1.2=pyh9f0ad1d_0
  - flask-compress=1.12=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=h2bbff1b_0
  - future=0.18.2=py39hcbf5309_5
  - gdal=3.0.2=py39hb978731_4
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_0
  - glpk=4.65=h2bbff1b_3
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.6=h1756f20_1
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.9.1=py39haa95532_0
  - ipympl=0.9.2=pyhd8ed1ab_0
  - ipython=8.4.0=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - jedi=0.18.1=py39haa95532_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.4.0=py39haa95532_0
  - jupyter_client=7.2.2=py39haa95532_0
  - jupyter_core=4.10.0=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - kealib=1.4.14=hde4a422_1
  - kiwisolver=1.4.2=py39hd77b12b_0
  - krb5=1.19.2=h5b6d351_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcurl=7.84.0=h86230a5_0
  - libgdal=3.0.2=ha304284_4
  - libiconv=1.16=h2bbff1b_2
  - libnetcdf=4.8.1=h6685c40_1
  - libpng=1.6.37=h2a8f88b_0
  - libpq=12.9=hb652d5d_3
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=4.3.0a=h14feca5_20
  - libssh2=1.10.0=hcd4344a_0
  - libtiff=4.2.0=he0120a3_1
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libzip=1.8.0=h49b8836_0
  - lz4-c=1.9.3=h2bbff1b_1
  - lzo=2.10=vc14h0a64fa6_1
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - mapclassify=2.4.3=pyhd3eb1b0_0
  - markupsafe=2.1.1=py39h2bbff1b_0
  - matplotlib-base=3.5.1=py39hd77b12b_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - mock=4.0.3=pyhd3eb1b0_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py39haa95532_0
  - nbconvert=6.4.4=py39haa95532_0
  - nbformat=5.3.0=py39haa95532_0
  - nest-asyncio=1.5.5=py39haa95532_0
  - networkx=2.8.4=py39haa95532_0
  - nose=1.3.7=py_1006
  - notebook=6.4.12=py39haa95532_0
  - numexpr=2.8.3=py39hb80d3ca_0
  - numpy=1.21.5=py39h7a0a035_3
  - numpy-base=1.21.5=py39hca35cd5_3
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1q=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39hd77b12b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hdc2b20a_1
  - pip=22.1.2=py39haa95532_0
  - plotly=5.10.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - proj=6.2.1=h3758d61_0
  - prometheus_client=0.14.1=py39haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyomo=6.4.2=py39h415ef7b_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py39h593ac45_1
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pytables=3.6.1=py39h56d22b6_1
  - python=3.9.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=py39haa95532_0
  - pyutilib=6.0.0=pyh9f0ad1d_0
  - pywin32=302=py39h2bbff1b_2
  - pywinpty=2.0.2=py39h5da7b33_0
  - pyyaml=6.0=py39hb82d6ee_4
  - pyzmq=23.2.0=py39hd77b12b_0
  - rtree=0.9.7=py39h2eaa2aa_1
  - scikit-learn=1.1.1=py39hd77b12b_0
  - scipy=1.7.3=py39h0a974cb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.39.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - terminado=0.13.1=py39haa95532_0
  - testpath=0.6.0=py39haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.3.3=h3649cd2_2
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.3.0=py39haa95532_0
  - typing_extensions=4.3.0=py39haa95532_0
  - tzdata=2022a=hda174b7_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39haa95532_1
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - wincertstore=0.2=py39haa95532_2
  - winpty=0.4.3=4
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h8cc25b3_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - charset-normalizer==2.1.0
    - idna==3.3
    - itsdangerous==2.0.1
    - mycolorpy==1.5.1
    - requests==2.28.1
    - shapely==1.8.2
    - umap==0.1.1
    - urllib3==1.26.11
    - wget==3.2
